version: '2'
services:
 mysql:
   image: mysql:5.7
   restart: always
   size: m3
   environment:
     - MYSQL_ROOT_PASSWORD=wordpress
     - MYSQL_DATABASE=wordpress
     - MYSQL_USER=wordpress
     - MYSQL_PASSWORD=wordpress
   noauto_volume: true
   expose:
     - "3306:3306"

wordpress:
   depends_on:
     - mysql
   image: wordpress:latest
   ports:
     - "80:80"
   noauto_volume: true
   size: m3
   restart: always
   fip: CHANGME
   environment:
     - WORDPRESS_DB_HOST=mysql:3306
     - WORDPRESS_DB_PASSWORD=wordpress
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_NAME=wordpress
   links:
     - mysql:mysql
